import AuthInitializer from "@/components/layout/AuthProvider/authinitializer";
import { inter, poppins } from "@/utils/font";
import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
    title: "Medium",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${poppins.className} bg-primary`}
            >
                <AuthInitializer>{children}</AuthInitializer>
            </body>
        </html>
    );
}
