import { inter, poppins } from "@/utils/font";
import type { Metadata } from "next";
import "./styles/globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Medium",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${poppins.variable} bg-primary`}>
                {children}
            </body>
        </html>
    );
}
